name = "OOPMacro"
uuid = "90c472d1-064c-5c63-af2e-229f1fdb5f26"
authors = ["Shih-Ming Wang <swang150@ucsc.edu>", "Marius Kruger <amanic@gmail.com>"]
version = "0.4.0"

[compat]
julia = ">= 0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
